---
- name: "Regather facts" # This is required as gather_facts is run without become rights at the start of the playbook
  setup:

- name: "Check for Media-vg Volume Group"
  fail:
    msg: "Media-vg Volume Group not found"
  when:
    - ansible_lvm['vgs']['Media-vg'] is not defined

- name: "Check for Media-lv Logical Volume"
  fail:
    msg: "Media-lv Logical Volume not found"
  when:
    - ansible_lvm['lvs']['Media-lv'] is not defined

- set_fact:
    mount_names: "{{ ansible_mounts | map(attribute='mount') | list }}"
- name: "Check if Media-lv is mounted"
  debug: msg="Checking if mount {{ item }} exists"
  loop: "{{ required_mounts }}"
  failed_when: item not in mount_names

- name: "Check if PlexMedia folders exist"
  stat:
    path: "{{ item }}"
  with_items: "{{ required_plex_folders }}"
  register: plex_folders_register

- name: "Verify PlexMedia folders exist"
  fail: msg="PlexMedia folder {{ item.item }} does not exist"
  loop: "{{ plex_folders_register.results }}"
  failed_when: not item.stat.exists or not item.stat.isdir

- name: "Add the plex user"
  user:
    name: "{{ plex_user }}"
    shell: /bin/bash
    state: present
    groups: plex,video,render
    append: false

- name: "Check if PlexMedia folders owner is PlexMedia user"
  fail: msg="PlexMedia folder {{ item.item }} is not owned by user {{ plex_user }}"
  loop: "{{ plex_folders_register.results }}"
  failed_when: item.stat.pw_name != plex_user